### ISSUE TITLE
Header is lowercased by Hyper

### ISSUE THREAD

**Issue by elbaro** [RedL0tus/rifling#1]
https://github.com/hyperium/hyper/issues/1539
Rifling fails to find "X-GitHub-Event" because Hyper 0.12 gives "x-github-event".

**Comment by elbaro** [comment]
Sorry, false alarm. It is working great.  Thanks for the nice library.

**Comment by RedL0tus** [comment]
Rifling will automatically convert the headers into lower case. Well, I still have something to say about this design.

In HTTP itself, the key of the headers seems to be case-insensitive. Hyper itself actually has a struct called HeaderMap for this type of usage (basically a HashMap with case-insensitive keys), but it is a hyper-specific thing. Rifling is kind of aimed to have the ability to work with several different web frameworks, so I converted the HeaderMap into a regular HashMap with lowercased keys. It is kind of a go-between decision though, maybe one day I will implement a HeaderMap for Rifling itself.

Anyway, I'm glad it works well for you.
